/**
 * @fileOverview Base de données locale complète pour les descriptions des 151 Pokémon de Kanto.
 * Fournit des indices instantanés en FR et EN sans appel API.
 */

export interface LocalHint {
  en: string;
  fr: string;
}

export const LOCAL_POKEDEX_HINTS: Record<number, LocalHint> = {
  1: { en: "A strange seed was planted on its back at birth. The plant sprouts and grows with this Pokémon.", fr: "Une graine étrange a été plantée sur son dos à sa naissance. Elle pousse avec lui." },
  2: { en: "When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs.", fr: "Lorsque le bulbe sur son dos grandit, il semble perdre la capacité de tenir sur ses pattes arrière." },
  3: { en: "The plant blooms by absorbing solar energy. It overlaps its petals to stay warm.", fr: "Sa fleur s'épanouit lorsqu'elle absorbe l'énergie solaire. Elle dégage un parfum apaisant." },
  4: { en: "The flame on its tail indicates its health. If it's healthy, the flame burns brightly.", fr: "La flamme au bout de sa queue indique son état de santé. Elle brûle fort s'il est en forme." },
  5: { en: "It has a barbaric nature. In battle, it whips its fiery tail and claws at its foe.", fr: "Il est de nature barbare. En combat, il utilise sa queue enflammée et ses griffes acérées." },
  6: { en: "A dragon-like Pokémon that flies in search of powerful opponents. It breathes intense fire.", fr: "Un Pokémon ressemblant à un dragon qui vole à la recherche d'adversaires puissants." },
  7: { en: "After birth, its back swells and hardens into a shell. Powerfully sprays bubbles from its mouth.", fr: "À sa naissance, son dos se gonfle et durcit pour former une carapace. Il crache de l'écume." },
  8: { en: "Often hides in water to stalk unwary prey. For swimming fast, it moves its ears to maintain balance.", fr: "Il se cache souvent dans l'eau. Pour nager vite, il bouge ses oreilles pour garder l'équilibre." },
  9: { en: "A brutal Pokémon with pressurized water jets on its shell. They are used for high speed tackles.", fr: "Un Pokémon brutal doté de canons à eau sur sa carapace. Il s'en sert pour charger à grande vitesse." },
  10: { en: "Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls.", fr: "Ses pattes courtes sont munies de ventouses qui lui permettent de grimper partout sans effort." },
  11: { en: "This Pokémon is vulnerable to attack while its shell is soft, exposing its weak and tender body.", fr: "Ce Pokémon est vulnérable tant que sa carapace est molle, révélant son corps fragile." },
  12: { en: "In battle, it flaps its wings at high speed to release highly toxic dust into the air.", fr: "En combat, il bat des ailes très vite pour libérer une poussière toxique dans l'air." },
  13: { en: "Often found in forests, eating leaves. It has a sharp venomous stinger on its head.", fr: "On le trouve souvent en forêt. Il possède un aiguillon venimeux très pointu sur la tête." },
  14: { en: "Almost incapable of moving, this Pokémon can only harden its shell to protect itself.", fr: "Presque incapable de bouger, il ne peut que durcir sa carapace pour se protéger." },
  15: { en: "Flies at high speed and attacks using its three venomous stingers on its forelegs and tail.", fr: "Vole à grande vitesse et attaque avec ses trois dards venimeux sur ses pattes et sa queue." },
  16: { en: "A common sight in forests and woods. It flaps its wings at ground level to kick up blinding sand.", fr: "Très commun dans les forêts. Il bat des ailes au sol pour soulever du sable aveuglant." },
  17: { en: "Very protective of its sprawling territorial area, this Pokémon will fiercely peck at any intruder.", fr: "Très protecteur de son territoire, il donne des coups de bec féroces à tout intrus." },
  18: { en: "When hunting, it skims the surface of water at high speed to pick off unwary prey such as Magikarp.", fr: "En chassant, il rase la surface de l'eau à grande vitesse pour attraper des Magicarpe." },
  19: { en: "Bites anything when it attacks. Small and very quick, it is a common sight in many places.", fr: "Il mord tout ce qu'il attaque. Petit et très rapide, on le voit un peu partout." },
  20: { en: "It uses its whiskers to maintain its balance. It apparently slows down if they are cut off.", fr: "Il utilise ses moustaches pour garder l'équilibre. Il ralentit si elles sont coupées." },
  21: { en: "Inept at flying high. However, it can fly very fast to protect its territory.", fr: "Incapable de voler très haut, il vole en revanche très vite pour protéger son territoire." },
  22: { en: "With its huge and magnificent wings, it can keep aloft without ever having to land for rest.", fr: "Avec ses grandes ailes magnifiques, il peut planer longtemps sans jamais se poser." },
  23: { en: "Moves silently and stealthily. It eats the eggs of birds, such as Pidgey and Spearow, whole.", fr: "Se déplace silencieusement. Il gobe les œufs d'oiseaux comme Roucool ou Piafabec." },
  24: { en: "It is rumored that the ferocious warning markings on its belly differ from area to area.", fr: "On raconte que les motifs effrayants sur son ventre varient d'une région à l'autre." },
  25: { en: "When several of these Pokémon gather, their electricity could build and cause lightning storms.", fr: "Quand plusieurs de ces Pokémon se réunissent, ils peuvent provoquer des orages." },
  26: { en: "Its long tail serves as a ground to protect itself from its own high voltage power.", fr: "Sa longue queue lui sert de mise à la terre pour se protéger de son propre voltage." },
  27: { en: "Burrows deep underground in arid locations far from water. It only emerges to hunt for food.", fr: "Creuse profondément dans les zones arides. Il ne sort que pour chercher de la nourriture." },
  28: { en: "Curls up into a spiny ball when threatened. It can roll along at high speed to attack or escape.", fr: "Se roule en boule piquante s'il est menacé. Il peut rouler très vite pour attaquer." },
  29: { en: "Although small, its venomous barbs render this Pokémon dangerous. The female has smaller horns.", fr: "Bien que petit, ses dards venimeux le rendent dangereux. La femelle a de petites cornes." },
  30: { en: "The female's horn develops slowly. Prefers physical attacks such as clawing and biting.", fr: "La corne de la femelle se développe lentement. Elle préfère mordre et griffer." },
  31: { en: "Its hard scales provide strong protection. It uses its hefty bulk to execute powerful moves.", fr: "Ses écailles dures le protègent bien. Il utilise sa masse pour des attaques puissantes." },
  32: { en: "Stiffens its ears to sense danger. The larger its horns, the more powerful its secreted venom.", fr: "Dresse ses oreilles pour sentir le danger. Plus ses cornes sont grandes, plus son venin est fort." },
  33: { en: "An aggressive Pokémon that is quick to attack. The horn on its head secretes a powerful venom.", fr: "Un Pokémon agressif qui attaque vite. La corne sur sa tête sécrète un venin puissant." },
  34: { en: "It uses its powerful tail in battle to smash, constrict, then break the prey's bones.", fr: "Il utilise sa queue puissante pour fracasser ou étouffer ses proies." },
  35: { en: "Its magical and cute appearance makes it a popular pet. It is extremely rare and difficult to find.", fr: "Son aspect mignon et magique en fait un animal prisé. Il est très rare à trouver." },
  36: { en: "A timid fairy Pokémon that is rarely seen. It will run and hide the moment it senses people.", fr: "Un Pokémon fée timide que l'on voit rarement. Il se cache dès qu'il sent une présence." },
  37: { en: "At the time of birth, it has only one tail. The tail splits from its tip as it grows older.", fr: "À sa naissance, il n'a qu'une queue. Elle se divise en plusieurs mèches en grandissant." },
  38: { en: "Very smart and very vindictive. Grabbing one of its many tails could result in a 1000-year curse.", fr: "Très intelligent et rancunier. Toucher à l'une de ses queues peut porter malheur pendant 1000 ans." },
  39: { en: "When its huge eyes light up, it sings a mysteriously soothing melody that lulls its enemies to sleep.", fr: "Quand ses yeux s'illuminent, il chante une mélodie mystérieuse qui endort ses ennemis." },
  40: { en: "The body is soft and rubbery. When angered, it will suck in air and inflate itself to an enormous size.", fr: "Son corps est mou et élastique. En colère, il aspire de l'air pour gonfler énormément." },
  41: { en: "Forms colonies in perpetually dark places. Uses ultrasonic waves to identify and locate objects.", fr: "Vit en colonie dans les lieux sombres. Utilise des ultrasons pour se repérer." },
  42: { en: "Once it strikes, it will not stop draining energy from the victim even if it gets too heavy to fly.", fr: "Une fois qu'il mord, il ne s'arrête plus de drainer l'énergie, même s'il devient trop lourd pour voler." },
  43: { en: "During the day, it keeps its face buried in the ground. At night, it wanders around sowing its seeds.", fr: "Le jour, il enterre sa tête dans le sol. La nuit, il erre en semant ses graines." },
  44: { en: "The fluid that oozes from its mouth isn't drool. It is a nectar that is used to attract prey.", fr: "Le liquide qui coule de sa bouche n'est pas de la bave, mais un nectar pour attirer ses proies." },
  45: { en: "It has the world's largest petals. With every step, the petals shake out heavy clouds of toxic pollen.", fr: "Il possède les plus grands pétales du monde. Il libère des nuages de pollen toxique." },
  46: { en: "Burrows to suck tree roots. The mushrooms on its back grow by drawing nutrients from the host insect.", fr: "Creuse pour sucer les racines. Les champignons sur son dos se nourrissent de l'insecte hôte." },
  47: { en: "A host-parasite pair in which the parasite mushroom has taken over the host bug. Prefers damp places.", fr: "Le champignon parasite a pris le contrôle de l'insecte. Il préfère les endroits humides." },
  48: { en: "Lives in the shadows of tall trees where it eats insects. It is attracted by light at night.", fr: "Vit à l'ombre des grands arbres et mange des insectes. Il est attiré par la lumière la nuit." },
  49: { en: "The dust-like scales covering its wings are color-coded to indicate the kinds of poison they contain.", fr: "La couleur des écailles sur ses ailes indique le type de poison qu'elles contiennent." },
  50: { en: "Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.", fr: "Vit à un mètre sous terre et se nourrit de racines. Il sort parfois la tête du sol." },
  51: { en: "A team of Diglett triplets. It triggers huge earthquakes by burrowing 60 miles underground.", fr: "Un trio de Taupiqueur. Il peut provoquer des séismes en creusant très profondément." },
  52: { en: "Adores circular objects. Wanders the streets on a nightly basis to look for dropped loose change.", fr: "Adore les objets ronds. Il rôde la nuit dans les rues à la recherche de pièces de monnaie." },
  53: { en: "Although its mature and elegant fur has many admirers, it is extremely difficult to raise as a pet.", fr: "Bien que sa fourrure élégante soit admirée, il est très difficile à apprivoiser." },
  54: { en: "While lulling its enemies with its vacant look, this wily Pokémon will use psychokinetic powers.", fr: "Il endort la vigilance de l'ennemi avec son regard vide avant d'utiliser ses pouvoirs psy." },
  55: { en: "Often seen swimming elegantly by lake shores. It is often mistaken for the Japanese monster Kappa.", fr: "Nage élégamment au bord des lacs. On le confond souvent avec un monstre légendaire." },
  56: { en: "Extremely quick to anger. It could be docile one moment then thrashing around the next.", fr: "Très facile à mettre en colère. Il peut être calme puis devenir furieux en un instant." },
  57: { en: "Always furious and tenacious to boot. It will not abandon chasing its quarry until it is caught.", fr: "Toujours furieux et tenace. Il ne s'arrête jamais de poursuivre sa proie." },
  58: { en: "Very protective of its territory. It will bark and bite to repel intruders from its space.", fr: "Très protecteur de son territoire. Il aboie et mord pour chasser les intrus." },
  59: { en: "A Pokémon that has been admired since the past for its beauty. It runs gracefully.", fr: "Un Pokémon admiré depuis longtemps pour sa beauté. Il court avec une grande grâce." },
  60: { en: "Its newly grown legs are unstable. It seems to prefer swimming over walking on land.", fr: "Ses pattes toutes neuves sont instables. Il préfère nager que marcher sur terre." },
  61: { en: "Capable of living in or out of water. When out of water, it sweats to keep its body slimy.", fr: "Peut vivre dans l'eau ou sur terre. Il transpire pour garder sa peau humide." },
  62: { en: "An adept swimmer at both the front crawl and breaststroke. Easily overtakes the best human swimmers.", fr: "Un nageur hors pair. Il dépasse facilement les meilleurs nageurs humains." },
  63: { en: "Using its ability to read minds, it will identify impending danger and teleport to safety.", fr: "Il utilise la télépathie pour sentir le danger et se téléporte immédiatement à l'abri." },
  64: { en: "It emits special alpha waves from its body that induce headaches just by being close by.", fr: "Il émet des ondes alpha qui provoquent des maux de tête à ceux qui l'approchent." },
  65: { en: "Its brain can outperform a super-computer. Its intelligence quotient is said to be 5000.", fr: "Son cerveau est plus puissant qu'un ordinateur. On dit que son QI est de 5000." },
  66: { en: "Loves to build its muscles. It trains in all styles of martial arts to become even stronger.", fr: "Adore muscler son corps. Il s'entraîne à tous les arts martiaux pour devenir plus fort." },
  67: { en: "Its muscular body is so powerful, it must wear a lead weight belt to regulate its motions.", fr: "Son corps est si puissant qu'il doit porter une ceinture pour limiter ses mouvements." },
  68: { en: "Using its heavy muscles, it throws powerful punches that can send the victim over the horizon.", fr: "Il utilise ses muscles puissants pour envoyer ses ennemis au-delà de l'horizon." },
  69: { en: "A carnivorous Pokémon that traps and eats bugs. It uses its root feet to soak up moisture.", fr: "Un Pokémon carnivore qui mange des insectes. Ses racines lui servent à boire." },
  70: { en: "It spits out poison powder to immobilize the enemy and then finishes it with a spray of acid.", fr: "Il crache de la poudre toxique pour paralyser l'ennemi avant de l'achever avec de l'acide." },
  71: { en: "Said to live in huge colonies deep in jungles, although no one has ever returned from there.", fr: "On dit qu'il vit en colonie dans la jungle, mais personne n'en est jamais revenu." },
  72: { en: "Drifts in shallow seas. Anglers who hook them by accident are often punished by its sting.", fr: "Flotte dans les eaux peu profondes. Les pêcheurs se font souvent piquer par accident." },
  73: { en: "The short tentacles stay hidden within the head. It can extend them to ensnare and sting prey.", fr: "Ses tentacules sont cachés dans sa tête. Il les déploie pour empoisonner ses proies." },
  74: { en: "Found in fields and mountains. Mistaking them for boulders, people often step on them.", fr: "Vit dans les montagnes. On les confond souvent avec des cailloux et on marche dessus." },
  75: { en: "Rolls down slopes to move. It rolls over any obstacle without slowing or changing its direction.", fr: "Il se déplace en roulant. Il écrase tout sur son passage sans jamais ralentir." },
  76: { en: "Its boulder-like body is extremely hard. It can easily withstand dynamite blasts.", fr: "Son corps de pierre est incroyablement dur. Il peut résister à des explosions de dynamite." },
  77: { en: "Its hooves are 10 times harder than diamonds. It can trample anything completely flat in little time.", fr: "Ses sabots sont 10 fois plus durs que le diamant. Il peut tout piétiner en un instant." },
  78: { en: "Very competitive, this Pokémon will chase anything that moves fast in the hopes of racing it.", fr: "Très compétitif, il poursuit tout ce qui bouge vite pour faire la course." },
  79: { en: "Incredibly slow and dopey. It takes 5 seconds for it to feel pain when under attack.", fr: "Incroyablement lent. Il lui faut 5 secondes pour ressentir la douleur d'une attaque." },
  80: { en: "The Shellder that is latched onto its tail is said to feed on the host's left over scraps.", fr: "Le Kokiyas accroché à sa queue se nourrirait des restes de son hôte." },
  81: { en: "Uses anti-gravity to stay suspended. Appears without warning and delivers Thunder Wave and similar moves.", fr: "Flotte grâce à l'anti-gravité. Il surgit sans prévenir pour lancer des vagues électriques." },
  82: { en: "Formed by several Magnemite linked together. They frequently appear when sunspots flare up.", fr: "Formé par l'union de plusieurs Magnéti. Ils apparaissent souvent lors d'orages magnétiques." },
  83: { en: "The sprig of green onions it holds is its weapon. It is used much like a metal sword.", fr: "Le poireau qu'il tient est son arme. Il s'en sert comme d'une épée en métal." },
  84: { en: "A bird that makes up for its poor flying with its fast footwork. Leaves giant footprints.", fr: "Un oiseau qui compense son mauvais vol par une course très rapide. Laisse de grandes traces." },
  85: { en: "Uses its three heads to execute complex schemes. While two heads sleep, one remains awake.", fr: "Ses trois têtes élaborent des plans complexes. Une tête veille pendant que les autres dorment." },
  86: { en: "The protruding horn on its head is very hard. It is used for bashing through thick ice.", fr: "La corne sur sa tête est très dure. Elle lui sert à briser la glace la plus épaisse." },
  87: { en: "Stores thermal energy within its body. It swims at a steady 8 knots even in frigid waters.", fr: "Stocke de la chaleur dans son corps. Il nage à 8 nœuds même dans les eaux glaciales." },
  88: { en: "Appears in filthy areas. Thrives by sucking up polluted sludge that is pumped out of factories.", fr: "Apparaît dans les lieux sales. Il se nourrit des boues polluées rejetées par les usines." },
  89: { en: "Thickly covered with a filthy, vile sludge. It is so toxic, even its footprints contain poison.", fr: "Couvert d'une boue toxique. Il est si sale que même ses traces de pas sont empoisonnées." },
  90: { en: "Its shell is as hard as diamond. Inside, it is very tender. It can only attack with its tongue.", fr: "Sa coquille est dure comme le diamant, mais l'intérieur est très tendre." },
  91: { en: "When attacked, it launches its spikes in quick succession. Its internal vital organs are never seen.", fr: "S'il est attaqué, il lance ses piques en rafale. On ne voit jamais ses organes internes." },
  92: { en: "Almost invisible, this gaseous Pokémon cloaks the target and lulls it to sleep without notice.", fr: "Presque invisible, ce Pokémon gazeux enveloppe sa proie pour l'endormir sans bruit." },
  93: { en: "Because of its ability to slip through block walls, it is said to be from another dimension.", fr: "Capable de traverser les murs, on raconte qu'il vient d'une autre dimension." },
  94: { en: "Under a full moon, this Pokémon likes to mimic the shadows of people and laugh at their fright.", fr: "Les nuits de pleine lune, il aime imiter l'ombre des gens pour se moquer de leur peur." },
  95: { en: "As it grows, the stone portions of its body harden to become similar to a black-colored diamond.", fr: "En grandissant, son corps de pierre durcit pour ressembler à du diamant noir." },
  96: { en: "Puts enemies to sleep then eats their dreams. Occasionally gets sick from eating bad dreams.", fr: "Endort ses ennemis pour manger leurs rêves. Il tombe parfois malade s'il mange un cauchemar." },
  97: { en: "When it locks eyes with an enemy, it will use a mix of PSI moves such as Hypnosis and Confusion.", fr: "S'il croise votre regard, il utilisera l'hypnose pour vous plonger dans la confusion." },
  98: { en: "Its pincers are not only powerful weapons, they are used for balance when walking sideways.", fr: "Ses pinces sont des armes puissantes, mais elles l'aident aussi à garder l'équilibre." },
  99: { en: "The large pincer has 10,000 hp of crushing power. However, its huge size makes it unwieldy.", fr: "Sa grande pince a une force incroyable, mais elle est si lourde qu'il a du mal à la bouger." },
  100: { en: "Usually found in power plants. Easily mistaken for a Poké Ball, it has zapped many people.", fr: "Vit dans les centrales. On le confond avec une Poké Ball, et il électrocute les imprudents." },
  101: { en: "It stores electric energy under very high pressure. It often explodes with little or no provocation.", fr: "Stocke l'électricité sous haute pression. Il explose souvent à la moindre provocation." },
  102: { en: "Often mistaken for eggs. When disturbed, they quickly gather and attack in swarms.", fr: "Souvent confondu avec des œufs. S'il est dérangé, le groupe attaque en essaim." },
  103: { en: "Legend has it that on rare occasions, one of its heads will drop off and continue on as an Exeggcute.", fr: "La légende dit qu'une de ses têtes tombe parfois pour redevenir un Noeunoeuf." },
  104: { en: "Because it never removes its skull helmet, no one has ever seen this Pokémon's real face.", fr: "Comme il ne retire jamais son casque en os, personne n'a jamais vu son vrai visage." },
  105: { en: "The bone it holds is its primary weapon. It throws the bone skillfully like a boomerang.", fr: "L'os qu'il tient est sa seule arme. Il le lance avec adresse comme un boomerang." },
  106: { en: "When in a hurry, its legs lengthen progressively. It runs smoothly with extra long, loping strides.", fr: "S'il est pressé, ses jambes s'allongent. Il court avec de grandes enjambées fluides." },
  107: { en: "While appearing to do nothing, it fires punches in lightning fast succession that are impossible to see.", fr: "Il semble immobile, mais il donne des coups de poing si rapides qu'ils sont invisibles." },
  108: { en: "Its tongue can be extended like a chameleon's. It leaves a tingling sensation when it licks enemies.", fr: "Sa langue s'étire comme celle d'un caméléon. Sa léche provoque des picotements." },
  109: { en: "Because it stores several kinds of toxic gases in its body, it is prone to exploding without warning.", fr: "Contient plusieurs gaz toxiques. Il peut exploser sans prévenir à tout moment." },
  110: { en: "Where two kinds of poison gases meet, two Koffing can fuse into a Weezing over many years.", fr: "Quand deux types de gaz se rencontrent, deux Smogo peuvent fusionner en un Smogogo." },
  111: { en: "Its massive bones are 1000 times harder than human bones. It can easily knock a trailer flying.", fr: "Ses os sont 1000 fois plus durs que les nôtres. Il peut envoyer valser un camion." },
  112: { en: "Protected by an armor-like hide, this Pokémon is capable of living in molten lava.", fr: "Protégé par une peau comme une armure, il peut vivre dans la lave en fusion." },
  113: { en: "A rare and elusive Pokémon that is said to bring happiness to those who manage to get it.", fr: "Un Pokémon rare qui porterait bonheur à celui qui réussit à l'attraper." },
  114: { en: "The whole body is swathed with wide vines that are similar to seaweed. Its vines shake as it walks.", fr: "Son corps est couvert de lianes bleues. Elles s'agitent quand il se déplace." },
  115: { en: "The infant rarely ventures out of its mother's protective pouch until it is 3 years old.", fr: "Le petit ne sort presque jamais de la poche de sa mère avant l'âge de 3 ans." },
  116: { en: "Known to shoot down flying bugs with precision blasts of ink from the surface of the water.", fr: "Connu pour abattre les insectes en plein vol avec des jets d'encre précis." },
  117: { en: "Capable of swimming backwards by rapidly flapping its wing-like pectoral fins and stout tail.", fr: "Capable de nager à reculons en agitant ses nageoires pectorales et sa queue." },
  118: { en: "Its tail fin billows like an elegant ballroom dress, giving it the nickname of the Water Queen.", fr: "Sa nageoire caudale ondule comme une robe, ce qui lui vaut le surnom de Reine des Eaux." },
  119: { en: "In the autumn spawning season, they can be seen swimming powerfully up rivers and creeks.", fr: "À l'automne, on peut les voir remonter vigoureusement les rivières pour pondre." },
  120: { en: "An enigmatic Pokémon that can effortlessly regenerate any appendage it loses in battle.", fr: "Un Pokémon énigmatique capable de régénérer n'importe quel membre perdu en combat." },
  121: { en: "Its central core glows with the seven colors of the rainbow. Some people value the core as a gem.", fr: "Son cœur brille des sept couleurs de l'arc-en-ciel. Certains le considèrent comme un bijou." },
  122: { en: "If interrupted while it is miming, it will suddenly slap the offender with its favorite hands.", fr: "S'il est dérangé pendant son numéro de mime, il gifle l'importun avec force." },
  123: { en: "With ninja-like agility and speed, it can create the illusion that there is more than one.", fr: "Avec son agilité de ninja, il peut créer l'illusion qu'il y en a plusieurs." },
  124: { en: "It seductively wiggles its hips as it walks. It can cause people to dance in unison with it.", fr: "Il ondule des hanches en marchant. Il peut forcer les gens à danser avec lui." },
  125: { en: "Normally found near power plants, they can wander away and cause major blackouts in cities.", fr: "Vit près des centrales électriques. Il peut causer de grandes pannes de courant en ville." },
  126: { en: "Its body always burns with an orange glow that enables it to hide perfectly among flames.", fr: "Son corps brûle d'un éclat orangé qui lui permet de se cacher dans les flammes." },
  127: { en: "If it fails to crush the victim in its pincers, it will swing it around and toss it hard.", fr: "S'il n'arrive pas à broyer sa proie, il la fait tournoyer avant de la projeter au loin." },
  128: { en: "When it targets an enemy, it charges furiously while whipping its body with its three long tails.", fr: "Quand il cible un ennemi, il charge avec fureur en se fouettant avec ses trois queues." },
  129: { en: "In the distant past, it was somewhat stronger than the horribly weak descendants that exist today.", fr: "Autrefois, il était bien plus fort que ses descendants actuels qui sont très faibles." },
  130: { en: "Rarely seen in the wild. Huge and vicious, it is capable of destroying entire cities in a rage.", fr: "Rare à l'état sauvage. Cruel, il peut détruire des villes entières dans sa fureur." },
  131: { en: "A Pokémon that has been over-hunted almost to extinction. It can ferry people across water.", fr: "Un Pokémon victime de la surpêche. Il peut transporter des gens sur son dos." },
  132: { en: "Capable of copying an enemy's genetic code to instantly transform itself into a duplicate of the foe.", fr: "Capable de copier le code génétique de l'ennemi pour se transformer en son double." },
  133: { en: "Its genetic code is irregular. It may mutate if it is exposed to radiation from element stones.", fr: "Son code génétique est instable. Il évolue selon la pierre élémentaire utilisée." },
  134: { en: "Lives near water. Its long tail is ridged with a fin which is often mistaken for a mermaid's.", fr: "Vit près de l'eau. On confond souvent sa nageoire caudale avec celle d'une sirène." },
  135: { en: "It accumulates negative ions from the atmosphere to blast out 10000-volt lightning bolts.", fr: "Il accumule des ions négatifs pour envoyer des éclairs de 10 000 volts." },
  136: { en: "When storing thermal energy in its body, its temperature could soar to over 1600 degrees.", fr: "Lorsqu'il emmagasine de la chaleur, sa température peut monter à 900 degrés." },
  137: { en: "A Pokémon that consists entirely of programming code. Capable of moving freely in cyberspace.", fr: "Un Pokémon constitué de code informatique. Il se déplace librement dans le cyberespace." },
  138: { en: "A Pokémon that was resurrected from a fossil found in what was once the ocean floor eons ago.", fr: "Un Pokémon ressuscité à partir d'un fossile trouvé au fond des océans." },
  139: { en: "Its sharp shell is very hard. It is thought that this Pokémon became extinct because its shell grew too large.", fr: "Sa coquille est très dure. On pense qu'il a disparu car elle était devenue trop lourde." },
  140: { en: "A Pokémon that was resurrected from a fossil. However, in rare cases, living examples have been found.", fr: "Un Pokémon ressuscité d'un fossile. Des spécimens vivants ont parfois été trouvés." },
  141: { en: "Its sleek shape is perfect for swimming. It slashes prey with its claws and drains the body fluids.", fr: "Sa forme est parfaite pour nager. Il déchiquette ses proies avec ses griffes acérées." },
  142: { en: "A ferocious, prehistoric Pokémon that goes for the enemy's throat with its serrated saw-like teeth.", fr: "Un Pokémon préhistorique féroce qui vise la gorge avec ses dents en dents de scie." },
  143: { en: "Very lazy. Just eats and sleeps. As its rotund bulk builds, it becomes even more slothful.", fr: "Très paresseux. Il ne fait que manger et dormir. Plus il grossit, plus il devient lent." },
  144: { en: "A legendary bird Pokémon that is said to appear to doomed people who are lost in icy mountains.", fr: "Un oiseau légendaire qui apparaîtrait aux personnes perdues dans les monts enneigés." },
  145: { en: "A legendary bird Pokémon that is said to appear from clouds while wielding enormous lightning bolts.", fr: "Un oiseau légendaire qui sortirait des nuages en lançant d'énormes éclairs." },
  146: { en: "Known as the legendary bird of fire. Every flap of its wings creates a dazzling flare of flames.", fr: "Connu comme l'oiseau légendaire du feu. Chaque battement d'ailes crée des flammes." },
  147: { en: "Long considered a mythical Pokémon until recently, when a small colony was found living underwater.", fr: "Longtemps considéré comme mythique, jusqu'à la découverte d'une colonie sous-marine." },
  148: { en: "A mystical Pokémon that exudes a gentle aura. Has the ability to change climate conditions.", fr: "Un Pokémon mystique à l'aura douce. Il est capable de changer le climat." },
  149: { en: "An extremely rarely seen marine Pokémon. Its intelligence is said to match that of humans.", fr: "Un Pokémon marin très rare. On dit que son intelligence égale celle des humains." },
  150: { en: "It was created by a scientist after years of horrific gene splicing and DNA engineering experiments.", fr: "Il a été créé par un scientifique après des années de manipulations génétiques." },
  151: { en: "So rare that it is still said to be a mirage by many experts. Only a few people have seen it.", fr: "Si rare que de nombreux experts pensent qu'il s'agit d'un mirage." }
};

export function getLocalHint(id: number, lang: 'en' | 'fr'): string | null {
  return LOCAL_POKEDEX_HINTS[id]?.[lang] || null;
}
