export interface PokemonEntry {
  id: number;
  name: {
    en: string;
    fr: string;
  };
}

export const POKEMON_151: PokemonEntry[] = [
  { id: 1, name: { en: "Bulbasaur", fr: "Bulbizarre" } },
  { id: 2, name: { en: "Ivysaur", fr: "Herbizarre" } },
  { id: 3, name: { en: "Venusaur", fr: "Florizarre" } },
  { id: 4, name: { en: "Charmander", fr: "Salamèche" } },
  { id: 5, name: { en: "Charmeleon", fr: "Reptincel" } },
  { id: 6, name: { en: "Charizard", fr: "Dracaufeu" } },
  { id: 7, name: { en: "Squirtle", fr: "Carapuce" } },
  { id: 8, name: { en: "Wartortle", fr: "Carabaffe" } },
  { id: 9, name: { en: "Blastoise", fr: "Tortank" } },
  { id: 10, name: { en: "Caterpie", fr: "Chenipan" } },
  { id: 11, name: { en: "Metapod", fr: "Chrysacier" } },
  { id: 12, name: { en: "Butterfree", fr: "Papilusion" } },
  { id: 13, name: { en: "Weedle", fr: "Aspicot" } },
  { id: 14, name: { en: "Kakuna", fr: "Coconfort" } },
  { id: 15, name: { en: "Beedrill", fr: "Dardargnan" } },
  { id: 16, name: { en: "Pidgey", fr: "Roucool" } },
  { id: 17, name: { en: "Pidgeotto", fr: "Roucoups" } },
  { id: 18, name: { en: "Pidgeot", fr: "Roucarnage" } },
  { id: 19, name: { en: "Rattata", fr: "Rattata" } },
  { id: 20, name: { en: "Raticate", fr: "Rattatac" } },
  { id: 21, name: { en: "Spearow", fr: "Piafabec" } },
  { id: 22, name: { en: "Fearow", fr: "Rapasdepic" } },
  { id: 23, name: { en: "Ekans", fr: "Abo" } },
  { id: 24, name: { en: "Arbok", fr: "Arbok" } },
  { id: 25, name: { en: "Pikachu", fr: "Pikachu" } },
  { id: 26, name: { en: "Raichu", fr: "Raichu" } },
  { id: 27, name: { en: "Sandshrew", fr: "Sabelette" } },
  { id: 28, name: { en: "Sandslash", fr: "Sablaireau" } },
  { id: 29, name: { en: "Nidoran♀", fr: "Nidoran♀" } },
  { id: 30, name: { en: "Nidorina", fr: "Nidorina" } },
  { id: 31, name: { en: "Nidoqueen", fr: "Nidoqueen" } },
  { id: 32, name: { en: "Nidoran♂", fr: "Nidoran♂" } },
  { id: 33, name: { en: "Nidorino", fr: "Nidorino" } },
  { id: 34, name: { en: "Nidoking", fr: "Nidoking" } },
  { id: 35, name: { en: "Clefairy", fr: "Mélofée" } },
  { id: 36, name: { en: "Clefable", fr: "Mélodelfe" } },
  { id: 37, name: { en: "Vulpix", fr: "Goupix" } },
  { id: 38, name: { en: "Ninetales", fr: "Feunard" } },
  { id: 39, name: { en: "Jigglypuff", fr: "Rondoudou" } },
  { id: 40, name: { en: "Wigglytuff", fr: "Grodoudou" } },
  { id: 41, name: { en: "Zubat", fr: "Nosferapti" } },
  { id: 42, name: { en: "Golbat", fr: "Nosferalto" } },
  { id: 43, name: { en: "Oddish", fr: "Mystherbe" } },
  { id: 44, name: { en: "Gloom", fr: "Ortide" } },
  { id: 45, name: { en: "Vileplume", fr: "Rafflesia" } },
  { id: 46, name: { en: "Paras", fr: "Paras" } },
  { id: 47, name: { en: "Parasect", fr: "Parasect" } },
  { id: 48, name: { en: "Venonat", fr: "Mimitoss" } },
  { id: 49, name: { en: "Venomoth", fr: "Aéromite" } },
  { id: 50, name: { en: "Diglett", fr: "Taupiqueur" } },
  { id: 51, name: { en: "Dugtrio", fr: "Triopikeur" } },
  { id: 52, name: { en: "Meowth", fr: "Miaouss" } },
  { id: 53, name: { en: "Persian", fr: "Persian" } },
  { id: 54, name: { en: "Psyduck", fr: "Psykokwak" } },
  { id: 55, name: { en: "Golduck", fr: "Akwakwak" } },
  { id: 56, name: { en: "Mankey", fr: "Férosinge" } },
  { id: 57, name: { en: "Primeape", fr: "Colossinge" } },
  { id: 58, name: { en: "Growlithe", fr: "Caninos" } },
  { id: 59, name: { en: "Arcanine", fr: "Arcanin" } },
  { id: 60, name: { en: "Poliwag", fr: "Ptitard" } },
  { id: 61, name: { en: "Poliwhirl", fr: "Tétarte" } },
  { id: 62, name: { en: "Poliwrath", fr: "Tartard" } },
  { id: 63, name: { en: "Abra", fr: "Abra" } },
  { id: 64, name: { en: "Kadabra", fr: "Kadabra" } },
  { id: 65, name: { en: "Alakazam", fr: "Alakazam" } },
  { id: 66, name: { en: "Machop", fr: "Machoc" } },
  { id: 67, name: { en: "Machoke", fr: "Machopeur" } },
  { id: 68, name: { en: "Machamp", fr: "Mackogneur" } },
  { id: 69, name: { en: "Bellsprout", fr: "Chétiflor" } },
  { id: 70, name: { en: "Weepinbell", fr: "Boustiflor" } },
  { id: 71, name: { en: "Victreebel", fr: "Empiflor" } },
  { id: 72, name: { en: "Tentacool", fr: "Tentacool" } },
  { id: 73, name: { en: "Tentacruel", fr: "Tentacruel" } },
  { id: 74, name: { en: "Geodude", fr: "Racaillou" } },
  { id: 75, name: { en: "Graveler", fr: "Gravalanch" } },
  { id: 76, name: { en: "Golem", fr: "Grolem" } },
  { id: 77, name: { en: "Ponyta", fr: "Ponyta" } },
  { id: 78, name: { en: "Rapidash", fr: "Galopa" } },
  { id: 79, name: { en: "Slowpoke", fr: "Ramoloss" } },
  { id: 80, name: { en: "Slowbro", fr: "Flagadoss" } },
  { id: 81, name: { en: "Magnemite", fr: "Magnéti" } },
  { id: 82, name: { en: "Magneton", fr: "Magnéton" } },
  { id: 83, name: { en: "Farfetch'd", fr: "Canarticho" } },
  { id: 84, name: { en: "Doduo", fr: "Doduo" } },
  { id: 85, name: { en: "Dodrio", fr: "Dodrio" } },
  { id: 86, name: { en: "Seel", fr: "Otaria" } },
  { id: 87, name: { en: "Dewgong", fr: "Lamantine" } },
  { id: 88, name: { en: "Grimer", fr: "Tas de Morve" } },
  { id: 89, name: { en: "Muk", fr: "Grotadmorv" } },
  { id: 90, name: { en: "Shellder", fr: "Kokiyas" } },
  { id: 91, name: { en: "Cloyster", fr: "Crustabri" } },
  { id: 92, name: { en: "Gastly", fr: "Fantominus" } },
  { id: 93, name: { en: "Haunter", fr: "Spectrum" } },
  { id: 94, name: { en: "Gengar", fr: "Ectoplasma" } },
  { id: 95, name: { en: "Onix", fr: "Onix" } },
  { id: 96, name: { en: "Drowzee", fr: "Soporifik" } },
  { id: 97, name: { en: "Hypno", fr: "Hypnomade" } },
  { id: 98, name: { en: "Krabby", fr: "Krabby" } },
  { id: 99, name: { en: "Kingler", fr: "Krabboss" } },
  { id: 100, name: { en: "Voltorb", fr: "Voltorbe" } },
  { id: 101, name: { en: "Electrode", fr: "Électrode" } },
  { id: 102, name: { en: "Exeggcute", fr: "Noeunoeuf" } },
  { id: 103, name: { en: "Exeggutor", fr: "Noadkoko" } },
  { id: 104, name: { en: "Cubone", fr: "Oselet" } },
  { id: 105, name: { en: "Marowak", fr: "Ossatueur" } },
  { id: 106, name: { en: "Hitmonlee", fr: "Kicklee" } },
  { id: 107, name: { en: "Hitmonchan", fr: "Tygnon" } },
  { id: 108, name: { en: "Lickitung", fr: "Excelangue" } },
  { id: 109, name: { en: "Koffing", fr: "Smogo" } },
  { id: 110, name: { en: "Weezing", fr: "Smogogo" } },
  { id: 111, name: { en: "Rhyhorn", fr: "Rhyhorn" } },
  { id: 112, name: { en: "Rhydon", fr: "Rhydon" } },
  { id: 113, name: { en: "Chansey", fr: "Leveinard" } },
  { id: 114, name: { en: "Tangela", fr: "Saquedeneu" } },
  { id: 115, name: { en: "Kangaskhan", fr: "Kangourex" } },
  { id: 116, name: { en: "Horsea", fr: "Hypotrempe" } },
  { id: 117, name: { en: "Seadra", fr: "Hypocéan" } },
  { id: 118, name: { en: "Goldeen", fr: "Poissirène" } },
  { id: 119, name: { en: "Seaking", fr: "Poissoroy" } },
  { id: 120, name: { en: "Staryu", fr: "Stari" } },
  { id: 121, name: { en: "Starmie", fr: "Staross" } },
  { id: 122, name: { en: "Mr. Mime", fr: "M. Mime" } },
  { id: 123, name: { en: "Scyther", fr: "Insécateur" } },
  { id: 124, name: { en: "Jynx", fr: "Lippoutou" } },
  { id: 125, name: { en: "Electabuzz", fr: "Élektek" } },
  { id: 126, name: { en: "Magmar", fr: "Magmar" } },
  { id: 127, name: { en: "Pinsir", fr: "Scarabrute" } },
  { id: 128, name: { en: "Tauros", fr: "Tauros" } },
  { id: 129, name: { en: "Magikarp", fr: "Magicrape" } },
  { id: 130, name: { en: "Gyarados", fr: "Léviator" } },
  { id: 131, name: { en: "Lapras", fr: "Lokhlass" } },
  { id: 132, name: { en: "Ditto", fr: "Métamorph" } },
  { id: 133, name: { en: "Eevee", fr: "Évoli" } },
  { id: 134, name: { en: "Vaporeon", fr: "Aquali" } },
  { id: 135, name: { en: "Jolteon", fr: "Voltali" } },
  { id: 136, name: { en: "Flareon", fr: "Pyroli" } },
  { id: 137, name: { en: "Porygon", fr: "Porygon" } },
  { id: 138, name: { en: "Omanyte", fr: "Amonita" } },
  { id: 139, name: { en: "Omastar", fr: "Amonistar" } },
  { id: 140, name: { en: "Kabuto", fr: "Kabuto" } },
  { id: 141, name: { en: "Kabutops", fr: "Kabutops" } },
  { id: 142, name: { en: "Aerodactyl", fr: "Ptéra" } },
  { id: 143, name: { en: "Snorlax", fr: "Ronflex" } },
  { id: 144, name: { en: "Articuno", fr: "Artikodin" } },
  { id: 145, name: { en: "Zapdos", fr: "Électhor" } },
  { id: 146, name: { en: "Moltres", fr: "Sulfura" } },
  { id: 147, name: { en: "Dratini", fr: "Minidraco" } },
  { id: 148, name: { en: "Dragonair", fr: "Draco" } },
  { id: 149, name: { en: "Dragonite", fr: "Dracolosse" } },
  { id: 150, name: { en: "Mewtwo", fr: "Mewtwo" } },
  { id: 151, name: { en: "Mew", fr: "Mew" } }
];

export function getPokemonImageUrl(id: number, official: boolean = false) {
  if (official) {
    return `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${id}.png`;
  }
  return `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${id}.png`;
}
