export interface PokemonEntry {
  id: number;
  name: {
    en: string;
    fr: string;
  };
  types: string[];
}

export const POKEMON_151: PokemonEntry[] = [
  { id: 1, name: { en: "Bulbasaur", fr: "Bulbizarre" }, types: ["grass", "poison"] },
  { id: 2, name: { en: "Ivysaur", fr: "Herbizarre" }, types: ["grass", "poison"] },
  { id: 3, name: { en: "Venusaur", fr: "Florizarre" }, types: ["grass", "poison"] },
  { id: 4, name: { en: "Charmander", fr: "Salamèche" }, types: ["fire"] },
  { id: 5, name: { en: "Charmeleon", fr: "Reptincel" }, types: ["fire"] },
  { id: 6, name: { en: "Charizard", fr: "Dracaufeu" }, types: ["fire", "flying"] },
  { id: 7, name: { en: "Squirtle", fr: "Carapuce" }, types: ["water"] },
  { id: 8, name: { en: "Wartortle", fr: "Carabaffe" }, types: ["water"] },
  { id: 9, name: { en: "Blastoise", fr: "Tortank" }, types: ["water"] },
  { id: 10, name: { en: "Caterpie", fr: "Chenipan" }, types: ["bug"] },
  { id: 11, name: { en: "Metapod", fr: "Chrysacier" }, types: ["bug"] },
  { id: 12, name: { en: "Butterfree", fr: "Papilusion" }, types: ["bug", "flying"] },
  { id: 13, name: { en: "Weedle", fr: "Aspicot" }, types: ["bug", "poison"] },
  { id: 14, name: { en: "Kakuna", fr: "Coconfort" }, types: ["bug", "poison"] },
  { id: 15, name: { en: "Beedrill", fr: "Dardargnan" }, types: ["bug", "poison"] },
  { id: 16, name: { en: "Pidgey", fr: "Roucool" }, types: ["normal", "flying"] },
  { id: 17, name: { en: "Pidgeotto", fr: "Roucoups" }, types: ["normal", "flying"] },
  { id: 18, name: { en: "Pidgeot", fr: "Roucarnage" }, types: ["normal", "flying"] },
  { id: 19, name: { en: "Rattata", fr: "Rattata" }, types: ["normal"] },
  { id: 20, name: { en: "Raticate", fr: "Rattatac" }, types: ["normal"] },
  { id: 21, name: { en: "Spearow", fr: "Piafabec" }, types: ["normal", "flying"] },
  { id: 22, name: { en: "Fearow", fr: "Rapasdepic" }, types: ["normal", "flying"] },
  { id: 23, name: { en: "Ekans", fr: "Abo" }, types: ["poison"] },
  { id: 24, name: { en: "Arbok", fr: "Arbok" }, types: ["poison"] },
  { id: 25, name: { en: "Pikachu", fr: "Pikachu" }, types: ["electric"] },
  { id: 26, name: { en: "Raichu", fr: "Raichu" }, types: ["electric"] },
  { id: 27, name: { en: "Sandshrew", fr: "Sabelette" }, types: ["ground"] },
  { id: 28, name: { en: "Sandslash", fr: "Sablaireau" }, types: ["ground"] },
  { id: 29, name: { en: "Nidoran♀", fr: "Nidoran♀" }, types: ["poison"] },
  { id: 30, name: { en: "Nidorina", fr: "Nidorina" }, types: ["poison"] },
  { id: 31, name: { en: "Nidoqueen", fr: "Nidoqueen" }, types: ["poison", "ground"] },
  { id: 32, name: { en: "Nidoran♂", fr: "Nidoran♂" }, types: ["poison"] },
  { id: 33, name: { en: "Nidorino", fr: "Nidorino" }, types: ["poison"] },
  { id: 34, name: { en: "Nidoking", fr: "Nidoking" }, types: ["poison", "ground"] },
  { id: 35, name: { en: "Clefairy", fr: "Mélofée" }, types: ["fairy"] },
  { id: 36, name: { en: "Clefable", fr: "Mélodelfe" }, types: ["fairy"] },
  { id: 37, name: { en: "Vulpix", fr: "Goupix" }, types: ["fire"] },
  { id: 38, name: { en: "Ninetales", fr: "Feunard" }, types: ["fire"] },
  { id: 39, name: { en: "Jigglypuff", fr: "Rondoudou" }, types: ["normal", "fairy"] },
  { id: 40, name: { en: "Wigglytuff", fr: "Grodoudou" }, types: ["normal", "fairy"] },
  { id: 41, name: { en: "Zubat", fr: "Nosferapti" }, types: ["poison", "flying"] },
  { id: 42, name: { en: "Golbat", fr: "Nosferalto" }, types: ["poison", "flying"] },
  { id: 43, name: { en: "Oddish", fr: "Mystherbe" }, types: ["grass", "poison"] },
  { id: 44, name: { en: "Gloom", fr: "Ortide" }, types: ["grass", "poison"] },
  { id: 45, name: { en: "Vileplume", fr: "Rafflesia" }, types: ["grass", "poison"] },
  { id: 46, name: { en: "Paras", fr: "Paras" }, types: ["bug", "grass"] },
  { id: 47, name: { en: "Parasect", fr: "Parasect" }, types: ["bug", "grass"] },
  { id: 48, name: { en: "Venonat", fr: "Mimitoss" }, types: ["bug", "poison"] },
  { id: 49, name: { en: "Venomoth", fr: "Aéromite" }, types: ["bug", "poison"] },
  { id: 50, name: { en: "Diglett", fr: "Taupiqueur" }, types: ["ground"] },
  { id: 51, name: { en: "Dugtrio", fr: "Triopikeur" }, types: ["ground"] },
  { id: 52, name: { en: "Meowth", fr: "Miaouss" }, types: ["normal"] },
  { id: 53, name: { en: "Persian", fr: "Persian" }, types: ["normal"] },
  { id: 54, name: { en: "Psyduck", fr: "Psykokwak" }, types: ["water"] },
  { id: 55, name: { en: "Golduck", fr: "Akwakwak" }, types: ["water"] },
  { id: 56, name: { en: "Mankey", fr: "Férosinge" }, types: ["fighting"] },
  { id: 57, name: { en: "Primeape", fr: "Colossinge" }, types: ["fighting"] },
  { id: 58, name: { en: "Growlithe", fr: "Caninos" }, types: ["fire"] },
  { id: 59, name: { en: "Arcanine", fr: "Arcanin" }, types: ["fire"] },
  { id: 60, name: { en: "Poliwag", fr: "Ptitard" }, types: ["water"] },
  { id: 61, name: { en: "Poliwhirl", fr: "Tétarte" }, types: ["water"] },
  { id: 62, name: { en: "Poliwrath", fr: "Tartard" }, types: ["water", "fighting"] },
  { id: 63, name: { en: "Abra", fr: "Abra" }, types: ["psychic"] },
  { id: 64, name: { en: "Kadabra", fr: "Kadabra" }, types: ["psychic"] },
  { id: 65, name: { en: "Alakazam", fr: "Alakazam" }, types: ["psychic"] },
  { id: 66, name: { en: "Machop", fr: "Machoc" }, types: ["fighting"] },
  { id: 67, name: { en: "Machoke", fr: "Machopeur" }, types: ["fighting"] },
  { id: 68, name: { en: "Machamp", fr: "Mackogneur" }, types: ["fighting"] },
  { id: 69, name: { en: "Bellsprout", fr: "Chétiflor" }, types: ["grass", "poison"] },
  { id: 70, name: { en: "Weepinbell", fr: "Boustiflor" }, types: ["grass", "poison"] },
  { id: 71, name: { en: "Victreebel", fr: "Empiflor" }, types: ["grass", "poison"] },
  { id: 72, name: { en: "Tentacool", fr: "Tentacool" }, types: ["water", "poison"] },
  { id: 73, name: { en: "Tentacruel", fr: "Tentacruel" }, types: ["water", "poison"] },
  { id: 74, name: { en: "Geodude", fr: "Racaillou" }, types: ["rock", "ground"] },
  { id: 75, name: { en: "Graveler", fr: "Gravalanch" }, types: ["rock", "ground"] },
  { id: 76, name: { en: "Golem", fr: "Grolem" }, types: ["rock", "ground"] },
  { id: 77, name: { en: "Ponyta", fr: "Ponyta" }, types: ["fire"] },
  { id: 78, name: { en: "Rapidash", fr: "Galopa" }, types: ["fire"] },
  { id: 79, name: { en: "Slowpoke", fr: "Ramoloss" }, types: ["water", "psychic"] },
  { id: 80, name: { en: "Slowbro", fr: "Flagadoss" }, types: ["water", "psychic"] },
  { id: 81, name: { en: "Magnemite", fr: "Magnéti" }, types: ["electric", "steel"] },
  { id: 82, name: { en: "Magneton", fr: "Magnéton" }, types: ["electric", "steel"] },
  { id: 83, name: { en: "Farfetch'd", fr: "Canarticho" }, types: ["normal", "flying"] },
  { id: 84, name: { en: "Doduo", fr: "Doduo" }, types: ["normal", "flying"] },
  { id: 85, name: { en: "Dodrio", fr: "Dodrio" }, types: ["normal", "flying"] },
  { id: 86, name: { en: "Seel", fr: "Otaria" }, types: ["water"] },
  { id: 87, name: { en: "Dewgong", fr: "Lamantine" }, types: ["water", "ice"] },
  { id: 88, name: { en: "Grimer", fr: "Tas de Morve" }, types: ["poison"] },
  { id: 89, name: { en: "Muk", fr: "Grotadmorv" }, types: ["poison"] },
  { id: 90, name: { en: "Shellder", fr: "Kokiyas" }, types: ["water"] },
  { id: 91, name: { en: "Cloyster", fr: "Crustabri" }, types: ["water", "ice"] },
  { id: 92, name: { en: "Gastly", fr: "Fantominus" }, types: ["ghost", "poison"] },
  { id: 93, name: { en: "Haunter", fr: "Spectrum" }, types: ["ghost", "poison"] },
  { id: 94, name: { en: "Gengar", fr: "Ectoplasma" }, types: ["ghost", "poison"] },
  { id: 95, name: { en: "Onix", fr: "Onix" }, types: ["rock", "ground"] },
  { id: 96, name: { en: "Drowzee", fr: "Soporifik" }, types: ["psychic"] },
  { id: 97, name: { en: "Hypno", fr: "Hypnomade" }, types: ["psychic"] },
  { id: 98, name: { en: "Krabby", fr: "Krabby" }, types: ["water"] },
  { id: 99, name: { en: "Kingler", fr: "Krabboss" }, types: ["water"] },
  { id: 100, name: { en: "Voltorb", fr: "Voltorbe" }, types: ["electric"] },
  { id: 101, name: { en: "Electrode", fr: "Électrode" }, types: ["electric"] },
  { id: 102, name: { en: "Exeggcute", fr: "Noeunoeuf" }, types: ["grass", "psychic"] },
  { id: 103, name: { en: "Exeggutor", fr: "Noadkoko" }, types: ["grass", "psychic"] },
  { id: 104, name: { en: "Cubone", fr: "Oselet" }, types: ["ground"] },
  { id: 105, name: { en: "Marowak", fr: "Ossatueur" }, types: ["ground"] },
  { id: 106, name: { en: "Hitmonlee", fr: "Kicklee" }, types: ["fighting"] },
  { id: 107, name: { en: "Hitmonchan", fr: "Tygnon" }, types: ["fighting"] },
  { id: 108, name: { en: "Lickitung", fr: "Excelangue" }, types: ["normal"] },
  { id: 109, name: { en: "Koffing", fr: "Smogo" }, types: ["poison"] },
  { id: 110, name: { en: "Weezing", fr: "Smogogo" }, types: ["poison"] },
  { id: 111, name: { en: "Rhyhorn", fr: "Rhinocorne" }, types: ["ground", "rock"] },
  { id: 112, name: { en: "Rhydon", fr: "Rhinoféros" }, types: ["ground", "rock"] },
  { id: 113, name: { en: "Chansey", fr: "Leveinard" }, types: ["normal"] },
  { id: 114, name: { en: "Tangela", fr: "Saquedeneu" }, types: ["grass"] },
  { id: 115, name: { en: "Kangaskhan", fr: "Kangourex" }, types: ["normal"] },
  { id: 116, name: { en: "Horsea", fr: "Hypotrempe" }, types: ["water"] },
  { id: 117, name: { en: "Seadra", fr: "Hypocéan" }, types: ["water"] },
  { id: 118, name: { en: "Goldeen", fr: "Poissirène" }, types: ["water"] },
  { id: 119, name: { en: "Seaking", fr: "Poissoroy" }, types: ["water"] },
  { id: 120, name: { en: "Staryu", fr: "Stari" }, types: ["water"] },
  { id: 121, name: { en: "Starmie", fr: "Staross" }, types: ["water", "psychic"] },
  { id: 122, name: { en: "Mr. Mime", fr: "M. Mime" }, types: ["psychic", "fairy"] },
  { id: 123, name: { en: "Scyther", fr: "Insécateur" }, types: ["bug", "flying"] },
  { id: 124, name: { en: "Jynx", fr: "Lippoutou" }, types: ["ice", "psychic"] },
  { id: 125, name: { en: "Electabuzz", fr: "Élektek" }, types: ["electric"] },
  { id: 126, name: { en: "Magmar", fr: "Magmar" }, types: ["fire"] },
  { id: 127, name: { en: "Pinsir", fr: "Scarabrute" }, types: ["bug"] },
  { id: 128, name: { en: "Tauros", fr: "Tauros" }, types: ["normal"] },
  { id: 129, name: { en: "Magikarp", fr: "Magicrape" }, types: ["water"] },
  { id: 130, name: { en: "Gyarados", fr: "Léviator" }, types: ["water", "flying"] },
  { id: 131, name: { en: "Lapras", fr: "Lokhlass" }, types: ["water", "ice"] },
  { id: 132, name: { en: "Ditto", fr: "Métamorph" }, types: ["normal"] },
  { id: 133, name: { en: "Eevee", fr: "Évoli" }, types: ["normal"] },
  { id: 134, name: { en: "Vaporeon", fr: "Aquali" }, types: ["water"] },
  { id: 135, name: { en: "Jolteon", fr: "Voltali" }, types: ["electric"] },
  { id: 136, name: { en: "Flareon", fr: "Pyroli" }, types: ["fire"] },
  { id: 137, name: { en: "Porygon", fr: "Porygon" }, types: ["normal"] },
  { id: 138, name: { en: "Omanyte", fr: "Amonita" }, types: ["rock", "water"] },
  { id: 139, name: { en: "Omastar", fr: "Amonistar" }, types: ["rock", "water"] },
  { id: 140, name: { en: "Kabuto", fr: "Kabuto" }, types: ["rock", "water"] },
  { id: 141, name: { en: "Kabutops", fr: "Kabutops" }, types: ["rock", "water"] },
  { id: 142, name: { en: "Aerodactyl", fr: "Ptéra" }, types: ["rock", "flying"] },
  { id: 143, name: { en: "Snorlax", fr: "Ronflex" }, types: ["normal"] },
  { id: 144, name: { en: "Articuno", fr: "Artikodin" }, types: ["ice", "flying"] },
  { id: 145, name: { en: "Zapdos", fr: "Électhor" }, types: ["electric", "flying"] },
  { id: 146, name: { en: "Moltres", fr: "Sulfura" }, types: ["fire", "flying"] },
  { id: 147, name: { en: "Dratini", fr: "Minidraco" }, types: ["dragon"] },
  { id: 148, name: { en: "Dragonair", fr: "Draco" }, types: ["dragon"] },
  { id: 149, name: { en: "Dragonite", fr: "Dracolosse" }, types: ["dragon", "flying"] },
  { id: 150, name: { en: "Mewtwo", fr: "Mewtwo" }, types: ["psychic"] },
  { id: 151, name: { en: "Mew", fr: "Mew" }, types: ["psychic"] }
];

export function getPokemonImageUrl(id: number, official: boolean = false) {
  if (official) {
    return `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${id}.png`;
  }
  return `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${id}.png`;
}
